loft_core.settings:
  type: mapping
  label: Settings
  mapping:
    loft_core_trackjs_token:
      type: 'NULL'
    test_mode_url_token:
      type: 'NULL'
    use_redirect_api:
      type: boolean
    loft_core_cache_bust_token:
      type: string
    smart_url_regex:
      type: string
