loft_core.settings:
  type: mapping
  label: Settings
  mapping:
    loft_core_trackjs_token:
      type: 'NULL'
    loft_core_testing_key:
      type: 'NULL'
    loft_core_node_redirects:
      type: boolean
    loft_core_cache_bust_token:
      type: string
    loft_core_mail_registration_from:
      type: string
