<?php
/**
 * @file
 * Base file for the loft_core_users module.
 *
 * @defgroup loft_core_users Loft Core Users
 * @{
 */

/**
 * This account was trapped as a robot.
 */
define('LOFT_CORE_USERS_STATUS_ROBOT', 2);

/**
 * This account was trapped by the honepot module.
 */
define('LOFT_CORE_USERS_STATUS_HONEYBEAR', 3);

/**
 * For one reason or another this account appears spammy.
 */
define('LOFT_CORE_USERS_STATUS_SPAMMY', 4);

/**
 * @var LOFT_CORE_USERS_HONEYPOT_REJECT_DOMAINS_WHITELIST
 *
 * CSV list of domains to whitelist that cannot be considered SPAM when
 * honeypot rejects.
 */
define('LOFT_CORE_USERS_HONEYPOT_REJECT_DOMAINS_WHITELIST', 'gmail.com');

/**
 * Implements hook_module_implements_alter().
 */
function loft_core_users_module_implements_alter(&$implementations, $hook)
{
    if ($hook == 'user_restrictions_alter') {
        // user_restrictions module overwrites our $error unless we call it first.
        $group = $implementations['loft_core_users'];
        unset($implementations['loft_core_users']);
        $implementations['loft_core_users'] = $group;
    }
}

/**
 * Return the domain of an email address.
 *
 * @param string $email
 *
 * @return string
 */
function _loft_core_users_get_email_domain($email)
{
    $domain = preg_replace('/^.+@/', '', $email);
    $domain = explode('.', $domain);

    return implode('.', array_slice($domain, -2));
}

/**
 * Block a user with optional augmented status.
 *
 * @param \stdClass $account
 * @param int       $status
 * @param string    $ip
 *
 * @see LOFT_CORE_USERS_STATUS_*
 */
function loft_core_users_block_user($uid, $mail, $status = 0, $ip = null)
{
    if ($status > 1) {
        loft_core_users_set_user_status($uid, $mail, $status, $ip);
    }
    $account = (object)[
        'uid' => $uid,
    ];
    user_block_user_action($account);
}


/**
 * Set the Loft Core status of a user.
 *
 * You MUST update users.status separate; this module does not handle that.
 *
 * @param $account
 * @param $status
 *
 * @see loft_core_users_block_user().
 */
function loft_core_users_set_user_status($uid, $mail, $status, $ip = null)
{
    $meta = [
        'uid' => $uid,
        'status' => $status,
        'domain' => _loft_core_users_get_email_domain($mail),
        'ip' => $ip,
    ];
    $meta = array_filter($meta);

    if ($uid) {
        $query = db_select('loft_core_users', 'lu')
            ->fields('lu', ['uid'])
            ->condition('uid', $uid);
        $primary_key = $query->execute()->fetchField() ? 'uid' : null;
        drupal_write_record('loft_core_users', $meta, $primary_key);
    }
    else {
        $exists = db_select('loft_core_users', 'lu')
            ->condition('uid', 0)
            ->condition('domain', $meta['domain'])
            ->countQuery()->execute()->fetchField();
        $primary_key = $exists ? ['uid', 'domain'] : null;
        drupal_write_record('loft_core_users', $meta, $primary_key);
    }
}

/**
 * This can be used as an menu page callback to trap robots.
 *
 * The basic idea is that if a visitor hits an url that they shouldn't then by
 * doing so they are exposing their nefarious intentions.  Their account will
 * immediately be blocked and they are logged out.  Watchdog messages will show
 * this has happened.
 *
 * To implement this feature, you need to modify a menu page callback.  And set
 * this function as the page callback.  In this next example we are going to
 * modify a node/add/user-collection to trap users.
 *
 * @code
 *   if (isset($items['node/add/user-collection'])) {
 *     array_unshift($items['node/add/user-collection']['page arguments'],
 *     $items['node/add/user-collection']['page callback']);
 *     $items['node/add/user-collection']['page callback'] =
 *     'loft_core_users_robotrap_page_callback';
 *   }
 * @endcode
 *
 * You MUST implement hook_loft_core_users_robotrap_access().
 * You MAY implement hook_loft_core_users_robotrap_goto_alter().
 */
function loft_core_users_robotrap_page_callback()
{
    global $user;
    $args = func_get_args();
    $callback = array_shift($args);
    $context = [
        'parent' => __FUNCTION__,
        'account' => $user,
        'page callback' => $callback,
        'page arguments' => $args,
    ];
    $access = module_invoke_all('loft_core_users_robotrap_access', $context);
    $access = end($access);
    if (!$access) {
        watchdog('loft_core', 'Robotrap: Blocked user %name.', ['%name' => $user->name]);
        loft_core_users_block_user($user->uid, $user->mail, LOFT_CORE_USERS_STATUS_ROBOT, ip_address());
        module_load_include('inc', 'user', 'user.pages');
        user_logout_current_user();
        drupal_set_message(t('You have visited a forbidden url; your account has been locked for review.  Please contact us using the form below to unlock your account.', ['!url' => url('contact', ['query' => ['cid' => 6]])]), 'warning', false);
        $path = module_exists('contact') ? 'contact' : '<front>';
        unset($_GET['destination']);
        $options = [];
        $context['parent'] = __FUNCTION__;
        drupal_alter('loft_core_robotrap_goto', $path, $options, $context);
        drupal_goto($path, $options);

        return false;
    }
    else {
        return call_user_func_array($callback, $args);
    }
}

/**
 * Implements hook_user_restrictions_alter().
 */
function loft_core_users_user_restrictions_alter(&$denied, &$error, &$context)
{
    // List all statuses which indicate a domain has been blocked.
    $statuses_which_block_users = [
        LOFT_CORE_USERS_STATUS_ROBOT,
        LOFT_CORE_USERS_STATUS_SPAMMY,
    ];

    //
    //
    // Restrict any email address whose domain matches that of an already robo-trapped user.
    //
    if ($context['type'] === 'mail') {

        // Check if the domain has been trapped.
        $domain = _loft_core_users_get_email_domain($context['form_state']['values']['mail']);
        $query = db_select('loft_core_users', 'lu')
            ->fields('lu', ['uid', 'domain'])
            ->condition('status', $statuses_which_block_users, 'IN')
            ->condition('domain', $domain);

        // If trapped, leverage user_restrictions module to block by email address.
        if ($is_suspicious = $query->execute()->fetchAllAssoc('uid')) {
            watchdog('loft_core', 'Suspicious Domain: Blocked new user @ %domain.', ['%domain' => $domain]);
            $context['mask'] = '*' . $domain;
            $denied = true;
            $error['field'] = 'mail';
            $contact = 'contact us';

            // With the contact module enabled we give an easy way for mistakes to get corrected.
            if (module_exists('contact')) {
                unset($_GET['destination']);
                $options = [];
                $path = 'contact';
                $contact = '<a href="!url">contact us</a>';
                $context['parent'] = __FUNCTION__;
                drupal_alter('loft_core_robotrap_goto', $path, $options, $context);
            }
            $error['message'] = t('Your email address is associated with a suspicious domain (%domain); please ' . $contact . ' if this is in error.', [
                '%domain' => $domain,
                '!url' => url($path, $options),
            ]);
        }
    }
}

/**
 * Implements hook_honeypot_reject().
 *
 * Make a note of this email address/user as a honeybear.
 */
function loft_core_users_honeypot_reject($form_id, $uid, $type)
{
    $g = data_api();
    if (($mail = $g->get($_POST, 'mail'))) {
        $domain = _loft_core_users_get_email_domain($mail);
        $default = explode(',', LOFT_CORE_USERS_HONEYPOT_REJECT_DOMAINS_WHITELIST);
        $may_block = !in_array($domain, variable_get('loft_core_users_honeypot_reject_domains_whitelist', $default));
        if ($may_block) {
            loft_core_users_set_user_status($uid, $mail, LOFT_CORE_USERS_STATUS_HONEYBEAR, ip_address());
        }
    }
}

function loft_core_users_user_block_spammy_user_action(&$entity, $context = array())
{
    // First priority: If there is a $entity->uid, block that user.
    // This is most likely a user object or the author if a node or comment.
    if (isset($entity->uid)) {
        $uid = $entity->uid;
    }
    elseif (isset($context['uid'])) {
        $uid = $context['uid'];
    }
    // If neither of those are valid, then block the current user.
    else {
        $uid = $GLOBALS['user']->uid;
    }
    $account = user_load($uid);
    loft_core_users_block_user($uid, $account->mail, LOFT_CORE_USERS_STATUS_SPAMMY);
}

/**
 * Implements hook_form_user_registration_alter().
 */
function loft_core_users_form_user_register_form_alter(&$form, &$form_state)
{
    $form['#submit'][] = 'loft_core_users_user_register_form_submit';
}

function loft_core_users_user_register_form_submit($form, $form_state)
{
    // When a new account is submitted, capture the IP.
    $account = $form_state['user'];
    loft_core_users_users_set_user_status($account->uid, $account->init, null, ip_address());
}
